### ISSUE TITLE
KeyError: 'km_product1_ATPM'

### ISSUE THREAD

**Issue by ghost** [EPFL-LCSB/rekindle#1]
Dear developer, 
I tried to repeat your example code and meet some errors.
1), the N1-rekindle-data-preprocessing.py cannot find the file in the 'models' folder. I solved this problem by downloading 'model.zip' from link https://zenodo.org/record/5803120#.YyvRuexByAk.
2), the N3-skimpy-calculate-eigenvalues.py cannot find 'km_product1_ATPM'.
It reports:
(rekindle) lijing@BIO-deep:~/rekindle/venv$ python N3-skimpy-calculate-eigenvalues.py 
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled
2022-09-23 11:12:26,863 - thermomodel_redGEMv1_MergedLMPDsAndBiomass - INFO - # Model initialized with units kcal/mol and temperature 298.15 K
2022-09-23 11:12:28,121 - Unnamed - WARNING - Non integer stoichiometries found ['LMPD_biomass_c_17_462'] change to integer for linear dependencies
2022-09-23 11:12:28,253 - Unnamed - WARNING - Non integer stoichiometries found ['LMPD_biomass_c_17_462'] change to integer for linear dependencies
kmodel compiled
Models and Data Loaded
Calculating eigenvalues.....
Models Processed: 0
Traceback (most recent call last):
  File "N3-skimpy-calculate-eigenvalues.py", line 29, in <module>
    _,max_eig = checkstability.calc_eigenvalues_recal_vmax()
  File "/home/lijing/rekindle/venv/skimpytools/stability.py", line 53, in calc_eigenvalues_recal_vmax
    param_val = ParameterValues(param_val,self.kmodel)
  File "/home/lijing/miniconda3/envs/rekindle/lib/python3.8/site-packages/skimpy-1.0.2-py3.8-linux-x86_64.egg/skimpy/core/parameters.py", line 59, in __init__
    self._sym_to_str = {self._str_to_sym[p]:p for p in self._parameter_values}
  File "/home/lijing/miniconda3/envs/rekindle/lib/python3.8/site-packages/skimpy-1.0.2-py3.8-linux-x86_64.egg/skimpy/core/parameters.py", line 59, in <dictcomp>
    self._sym_to_str = {self._str_to_sym[p]:p for p in self._parameter_values}
KeyError: 'km_product1_ATPM'

Could you please help me with the problem? Many thanks!

Best wishes,
Jing Li
PhD student in AOP
Xi'an jiaotong-liverpool University
Institute of Systems, Molecular and Integrative Biology 
University of Liverpool
jing.li1902@student.xjtlu.edu.cn

**Comment by ghost** [comment]
skimpy  version 1.0.2
